# GitHub Sponsors funding options
# github: # Add your GitHub username here if you want to enable GitHub Sponsors
# patreon: # Add your Patreon username
# open_collective: # Add your Open Collective username
# ko_fi: # Add your Ko-fi username
# tidelift: # Add your Tidelift package name
# community_bridge: # Add your Community Bridge project name
# liberapay: # Add your Liberapay username
# issuehunt: # Add your IssueHunt username
# otechie: # Add your Otechie username
# lfx_crowdfunding: # Add your LFX Crowdfunding project name
# custom: # Add up to 4 custom sponsorship URLs
