version: '3.8'

services:
  sentinel-guard:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
    volumes:
      # Mount volumes for persistent data
      - quarantine_data:/app/quarantine
      - scan_logs:/app/logs
      - app_data:/app/app-data
    restart: unless-stopped
    
  # Development service
  sentinel-guard-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
      - "9229:9229" # Debug port
    environment:
      - NODE_ENV=development
      - NEXT_TELEMETRY_DISABLED=1
    volumes:
      - .:/app
      - /app/node_modules
      - quarantine_data:/app/quarantine
      - scan_logs:/app/logs
      - app_data:/app/app-data
    command: npm run dev
    profiles:
      - dev

volumes:
  quarantine_data:
  scan_logs:
  app_data:
