name: ✨ Feature Request
description: Suggest an idea for Sentinel Guard
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a new feature! We appreciate your input and want to make sure we understand your idea completely.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe the problem you're trying to solve.
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see implemented.
      placeholder: I would like to see...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Describe any alternative solutions or features you've considered.
      placeholder: I've also considered...

  - type: dropdown
    id: priority
    attributes:
      label: Priority Level
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would improve workflow
        - High - Critical for my use case
    validations:
      required: true

  - type: checkboxes
    id: categories
    attributes:
      label: Feature Categories
      description: Which areas does this feature relate to? (Select all that apply)
      options:
        - label: User Interface/Experience
        - label: Scanning Engine
        - label: Security Features
        - label: Performance
        - label: Notifications
        - label: File Management
        - label: Settings/Configuration
        - label: Quarantine Management
        - label: Analytics/Reporting
        - label: Integration (APIs, third-party tools)

  - type: textarea
    id: mockups
    attributes:
      label: Mockups/Examples
      description: If applicable, add mockups, screenshots, or examples to help explain your feature request.
      placeholder: Drag and drop images here or paste them directly

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, links, or examples about the feature request here.
