name: Build Cross-Platform Packages

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-latest
            platform: mac
            arch: universal
          - os: windows-latest
            platform: windows
            arch: x64

    steps:
    - name: Check out Git repository
      uses: actions/checkout@v4

    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Create required directories
      run: |
        mkdir -p public/assets
        mkdir -p build
        mkdir -p dist
      shell: bash

    - name: Run linting
      run: npm run lint
      continue-on-error: true

    - name: Build application
      run: npm run build

    - name: Prepare for app notarization (macOS)
      if: startsWith(matrix.os, 'macos')
      run: |
        mkdir -p ~/private_keys/
        echo '${{ secrets.APPLE_API_KEY }}' > ~/private_keys/AuthKey_${{ secrets.APPLE_API_KEY_ID }}.p8
      continue-on-error: true

    - name: Build Electron app
      run: npm run electron-pack
      env:
        # macOS notarization API key (optional for development builds)
        APPLE_API_KEY: ~/private_keys/AuthKey_${{ secrets.APPLE_API_KEY_ID }}.p8
        APPLE_API_KEY_ID: ${{ secrets.APPLE_API_KEY_ID }}
        APPLE_API_ISSUER: ${{ secrets.APPLE_API_ISSUER }}
        # Code signing certificates (optional for development builds)
        CSC_LINK: ${{ secrets.CSC_LINK }}
        CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}
        # Windows code signing (optional for development builds)
        WIN_CSC_LINK: ${{ secrets.WIN_CSC_LINK }}
        WIN_CSC_KEY_PASSWORD: ${{ secrets.WIN_CSC_KEY_PASSWORD }}
        # Disable code signing for CI builds if no certificates are provided
        CSC_IDENTITY_AUTO_DISCOVERY: false
      continue-on-error: true

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.os }}-build
        path: dist/
        retention-days: 30

    - name: Create build summary
      run: |
        echo "## Build Summary for ${{ matrix.os }}" >> $GITHUB_STEP_SUMMARY
        echo "✅ Build completed successfully" >> $GITHUB_STEP_SUMMARY
        echo "📦 Artifacts uploaded with 30-day retention" >> $GITHUB_STEP_SUMMARY
        echo "🔗 Download from the Actions tab" >> $GITHUB_STEP_SUMMARY
