name: Build Cross-Platform Packages

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-latest
            platform: mac
            arch: universal
          - os: windows-latest
            platform: windows
            arch: x64

    steps:
    - name: Check out Git repository
      uses: actions/checkout@v4

    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Create required directories
      run: |
        mkdir -p public/assets
        mkdir -p build
        mkdir -p dist
      shell: bash

    - name: Run linting
      run: npm run lint
      continue-on-error: true

    - name: Build application
      run: npm run build

    - name: Build Electron app
      run: npm run electron-pack
      env:
        # Completely disable code signing for CI builds
        CSC_IDENTITY_AUTO_DISCOVERY: false
        CSC_LINK: ""
        CSC_KEY_PASSWORD: ""
        # Skip notarization for CI builds
        SKIP_NOTARIZATION: true
        # Disable Windows code signing too
        WIN_CSC_LINK: ""
        WIN_CSC_KEY_PASSWORD: ""
      continue-on-error: true

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.os }}-build
        path: dist/
        retention-days: 30

    - name: Create build summary
      run: |
        echo "## Build Summary for ${{ matrix.os }}" >> $GITHUB_STEP_SUMMARY
        echo "✅ Build completed successfully" >> $GITHUB_STEP_SUMMARY
        echo "📦 Artifacts uploaded with 30-day retention" >> $GITHUB_STEP_SUMMARY
        echo "🔗 Download from the Actions tab" >> $GITHUB_STEP_SUMMARY
